default: &default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default
  cable:
    <<: *cable
    url: <%= ENV['DATABASE_URL']&.+('_cable') %>

test:
  primary:
    <<: *default
  cable:
    <<: *cable
    url: <%= ENV['DATABASE_URL']&.+('_cable') %>

production:
  primary:
    <<: *default
  cable:
    <<: *cable
    url: <%= ENV['DATABASE_URL']&.+('_cable') %>
