terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "3.0.2-rc03"
    }
  }
}

provider "proxmox" {
  pm_api_url = var.api_url
  pm_user = var.username
  pm_password = var.password
  pm_tls_insecure = true
}

resource "proxmox_lxc" "container" {
  target_node = var.node

  hostname     = var.name
  ostemplate   = "local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"
  password     = "supersecret"

  cores        = 1
  memory       = 512
  swap         = 512
  start        = true
  rootfs {
    storage = "storage"
    size    = "8G"
  }

  network {
    name   = "eth0"
    bridge = "vmbr0"
    ip     = var.ip_address
    gw     = var.gateway
  }

  ssh_public_keys = var.ssh_public_key
  
  # DBChest provisioning via SSH (cloud-init-style script execution)
  # Note: Using SSH provisioners instead of native cloud-init for better LXC compatibility
  
  provisioner "remote-exec" {
    # Wait for container to be ready
    inline = [
      "while ! systemctl is-active --quiet ssh; do echo 'Waiting for SSH service...'; sleep 5; done",
      "echo 'Container is ready for DBChest provisioning'"
    ]
    
    connection {
      type        = "ssh"
      user        = "root"
      private_key = var.ssh_private_key
      host        = split("/", self.network[0].ip)[0]
      timeout     = "5m"
    }
  }
  
  provisioner "file" {
    # Deploy the DBChest setup script (generated by CloudInitService)
    content     = base64decode(var.cloud_init_user_data)
    destination = "/tmp/dbchest_setup.sh"
    
    connection {
      type        = "ssh"
      user        = "root"
      private_key = var.ssh_private_key
      host        = split("/", self.network[0].ip)[0]
      timeout     = "2m"
    }
  }
  
  provisioner "remote-exec" {
    # Execute the DBChest setup script with proper session detachment
    inline = [
      "chmod +x /tmp/dbchest_setup.sh",
      "echo 'Starting DBChest setup...'",
      "echo 'Script content preview:'",
      "head -10 /tmp/dbchest_setup.sh",
      "echo 'Creating detached wrapper...'",
      # Create a wrapper script that properly detaches from the SSH session
      "cat > /tmp/dbchest_wrapper.sh << 'EOF'",
      "#!/bin/bash",
      "# Detach from parent process completely and redirect all I/O",
      "nohup setsid /tmp/dbchest_setup.sh > /var/log/dbchest-setup.log 2>&1 < /dev/null &",
      "exit 0",
      "EOF",
      "chmod +x /tmp/dbchest_wrapper.sh",
      "echo 'Starting DBChest setup in detached session...'",
      # Run the wrapper which will detach completely and exit
      "/tmp/dbchest_wrapper.sh",
      "sleep 2",
      "echo 'DBChest setup started and detached from SSH session'",
      "echo 'Monitor progress with: tail -f /var/log/dbchest-setup.log'",
      "echo 'Check if running with: ps aux | grep dbchest_setup.sh'"
    ]
    
    connection {
      type        = "ssh"
      user        = "root"
      private_key = var.ssh_private_key
      host        = split("/", self.network[0].ip)[0]
      timeout     = "5m"
    }
  }

  # name        = "VM-name"
  #disks {
  #  ide {
  #    ide0 {
  #      cdrom {
  #        iso = "ubuntu-20.04.2-live-server-amd64.iso"
  #      }
  #    }
  #  }
  #  scsi {
  #    scsi0 {
  #      disk {
  #        size = "10"
  #        storage = "vmdisks"
  #      }
  #    }
  #  }
  #}
}

output "vmid" {
  value = proxmox_lxc.container.vmid
}

output "node" {
  value = var.node
}

output "ip_address" {
  value = var.ip_address
}

output "network_interfaces" {
  value = proxmox_lxc.container.network
}
